import type { CountryOption } from "@/types/auth";

type RawCountry = { name: string; isoCode: string; dialCode: string };

function normalizeDialCode(value: string) {
  // Some datasets include values like "1-684" (American Samoa). We keep digits only.
  return String(value ?? "").replace(/[^0-9]/g, "");
}

// Full list sourced from a standard ISO2 + phonecode dataset.
const RAW_COUNTRIES: RawCountry[] = [
  { name: "Afghanistan", isoCode: "AF", dialCode: "93" },
  { name: "Albania", isoCode: "AL", dialCode: "355" },
  { name: "Algeria", isoCode: "DZ", dialCode: "213" },
  { name: "American Samoa", isoCode: "AS", dialCode: "1-684" },
  { name: "Andorra", isoCode: "AD", dialCode: "376" },
  { name: "Angola", isoCode: "AO", dialCode: "244" },
  { name: "Anguilla", isoCode: "AI", dialCode: "1-264" },
  { name: "Antarctica", isoCode: "AQ", dialCode: "672" },
  { name: "Antigua And Barbuda", isoCode: "AG", dialCode: "1-268" },
  { name: "Argentina", isoCode: "AR", dialCode: "54" },
  { name: "Armenia", isoCode: "AM", dialCode: "374" },
  { name: "Aruba", isoCode: "AW", dialCode: "297" },
  { name: "Australia", isoCode: "AU", dialCode: "61" },
  { name: "Austria", isoCode: "AT", dialCode: "43" },
  { name: "Azerbaijan", isoCode: "AZ", dialCode: "994" },
  { name: "Bahamas The", isoCode: "BS", dialCode: "1-242" },
  { name: "Bahrain", isoCode: "BH", dialCode: "973" },
  { name: "Bangladesh", isoCode: "BD", dialCode: "880" },
  { name: "Barbados", isoCode: "BB", dialCode: "1-246" },
  { name: "Belarus", isoCode: "BY", dialCode: "375" },
  { name: "Belgium", isoCode: "BE", dialCode: "32" },
  { name: "Belize", isoCode: "BZ", dialCode: "501" },
  { name: "Benin", isoCode: "BJ", dialCode: "229" },
  { name: "Bermuda", isoCode: "BM", dialCode: "1-441" },
  { name: "Bhutan", isoCode: "BT", dialCode: "975" },
  { name: "Bolivia", isoCode: "BO", dialCode: "591" },
  { name: "Bosnia and Herzegovina", isoCode: "BA", dialCode: "387" },
  { name: "Botswana", isoCode: "BW", dialCode: "267" },
  { name: "Bouvet Island", isoCode: "BV", dialCode: "0055" },
  { name: "Brazil", isoCode: "BR", dialCode: "55" },
  { name: "British Indian Ocean Territory", isoCode: "IO", dialCode: "246" },
  { name: "Brunei", isoCode: "BN", dialCode: "673" },
  { name: "Bulgaria", isoCode: "BG", dialCode: "359" },
  { name: "Burkina Faso", isoCode: "BF", dialCode: "226" },
  { name: "Burundi", isoCode: "BI", dialCode: "257" },
  { name: "Cambodia", isoCode: "KH", dialCode: "855" },
  { name: "Cameroon", isoCode: "CM", dialCode: "237" },
  { name: "Canada", isoCode: "CA", dialCode: "1" },
  { name: "Cape Verde", isoCode: "CV", dialCode: "238" },
  { name: "Cayman Islands", isoCode: "KY", dialCode: "1-345" },
  { name: "Central African Republic", isoCode: "CF", dialCode: "236" },
  { name: "Chad", isoCode: "TD", dialCode: "235" },
  { name: "Chile", isoCode: "CL", dialCode: "56" },
  { name: "China", isoCode: "CN", dialCode: "86" },
  { name: "Christmas Island", isoCode: "CX", dialCode: "61" },
  { name: "Cocos (Keeling) Islands", isoCode: "CC", dialCode: "61" },
  { name: "Colombia", isoCode: "CO", dialCode: "57" },
  { name: "Comoros", isoCode: "KM", dialCode: "269" },
  { name: "Congo", isoCode: "CG", dialCode: "242" },
  { name: "Congo The Democratic Republic Of The", isoCode: "CD", dialCode: "243" },
  { name: "Cook Islands", isoCode: "CK", dialCode: "682" },
  { name: "Costa Rica", isoCode: "CR", dialCode: "506" },
  { name: "Cote D'Ivoire (Ivory Coast)", isoCode: "CI", dialCode: "225" },
  { name: "Croatia (Hrvatska)", isoCode: "HR", dialCode: "385" },
  { name: "Cuba", isoCode: "CU", dialCode: "53" },
  { name: "Cyprus", isoCode: "CY", dialCode: "357" },
  { name: "Czech Republic", isoCode: "CZ", dialCode: "420" },
  { name: "Denmark", isoCode: "DK", dialCode: "45" },
  { name: "Djibouti", isoCode: "DJ", dialCode: "253" },
  { name: "Dominica", isoCode: "DM", dialCode: "1-767" },
  { name: "Dominican Republic", isoCode: "DO", dialCode: "1-809" },
  { name: "Dominican Republic", isoCode: "DO", dialCode: "1-829" },
  { name: "Dominican Republic", isoCode: "DO", dialCode: "1-849" },
  { name: "East Timor", isoCode: "TL", dialCode: "670" },
  { name: "Ecuador", isoCode: "EC", dialCode: "593" },
  { name: "Egypt", isoCode: "EG", dialCode: "20" },
  { name: "El Salvador", isoCode: "SV", dialCode: "503" },
  { name: "Equatorial Guinea", isoCode: "GQ", dialCode: "240" },
  { name: "Eritrea", isoCode: "ER", dialCode: "291" },
  { name: "Estonia", isoCode: "EE", dialCode: "372" },
  { name: "Eswatini", isoCode: "SZ", dialCode: "268" },
  { name: "Ethiopia", isoCode: "ET", dialCode: "251" },
  { name: "Falkland Islands", isoCode: "FK", dialCode: "500" },
  { name: "Faroe Islands", isoCode: "FO", dialCode: "298" },
  { name: "Fiji Islands", isoCode: "FJ", dialCode: "679" },
  { name: "Finland", isoCode: "FI", dialCode: "358" },
  { name: "France", isoCode: "FR", dialCode: "33" },
  { name: "French Guiana", isoCode: "GF", dialCode: "594" },
  { name: "French Polynesia", isoCode: "PF", dialCode: "689" },
  { name: "French Southern Territories", isoCode: "TF", dialCode: "262" },
  { name: "Gabon", isoCode: "GA", dialCode: "241" },
  { name: "Gambia The", isoCode: "GM", dialCode: "220" },
  { name: "Georgia", isoCode: "GE", dialCode: "995" },
  { name: "Germany", isoCode: "DE", dialCode: "49" },
  { name: "Ghana", isoCode: "GH", dialCode: "233" },
  { name: "Gibraltar", isoCode: "GI", dialCode: "350" },
  { name: "Greece", isoCode: "GR", dialCode: "30" },
  { name: "Greenland", isoCode: "GL", dialCode: "299" },
  { name: "Grenada", isoCode: "GD", dialCode: "1-473" },
  { name: "Guadeloupe", isoCode: "GP", dialCode: "590" },
  { name: "Guam", isoCode: "GU", dialCode: "1-671" },
  { name: "Guatemala", isoCode: "GT", dialCode: "502" },
  { name: "Guernsey and Alderney", isoCode: "GG", dialCode: "44-1481" },
  { name: "Guinea", isoCode: "GN", dialCode: "224" },
  { name: "Guinea-Bissau", isoCode: "GW", dialCode: "245" },
  { name: "Guyana", isoCode: "GY", dialCode: "592" },
  { name: "Haiti", isoCode: "HT", dialCode: "509" },
  { name: "Heard Island and McDonald Islands", isoCode: "HM", dialCode: "672" },
  { name: "Honduras", isoCode: "HN", dialCode: "504" },
  { name: "Hong Kong S.A.R.", isoCode: "HK", dialCode: "852" },
  { name: "Hungary", isoCode: "HU", dialCode: "36" },
  { name: "Iceland", isoCode: "IS", dialCode: "354" },
  { name: "India", isoCode: "IN", dialCode: "91" },
  { name: "Indonesia", isoCode: "ID", dialCode: "62" },
  { name: "Iran", isoCode: "IR", dialCode: "98" },
  { name: "Iraq", isoCode: "IQ", dialCode: "964" },
  { name: "Ireland", isoCode: "IE", dialCode: "353" },
  { name: "Israel", isoCode: "IL", dialCode: "972" },
  { name: "Italy", isoCode: "IT", dialCode: "39" },
  { name: "Jamaica", isoCode: "JM", dialCode: "1-876" },
  { name: "Japan", isoCode: "JP", dialCode: "81" },
  { name: "Jersey", isoCode: "JE", dialCode: "44-1534" },
  { name: "Jordan", isoCode: "JO", dialCode: "962" },
  { name: "Kazakhstan", isoCode: "KZ", dialCode: "7" },
  { name: "Kenya", isoCode: "KE", dialCode: "254" },
  { name: "Kiribati", isoCode: "KI", dialCode: "686" },
  { name: "Korea North", isoCode: "KP", dialCode: "850" },
  { name: "Korea South", isoCode: "KR", dialCode: "82" },
  { name: "Kuwait", isoCode: "KW", dialCode: "965" },
  { name: "Kyrgyzstan", isoCode: "KG", dialCode: "996" },
  { name: "Laos", isoCode: "LA", dialCode: "856" },
  { name: "Latvia", isoCode: "LV", dialCode: "371" },
  { name: "Lebanon", isoCode: "LB", dialCode: "961" },
  { name: "Lesotho", isoCode: "LS", dialCode: "266" },
  { name: "Liberia", isoCode: "LR", dialCode: "231" },
  { name: "Libya", isoCode: "LY", dialCode: "218" },
  { name: "Liechtenstein", isoCode: "LI", dialCode: "423" },
  { name: "Lithuania", isoCode: "LT", dialCode: "370" },
  { name: "Luxembourg", isoCode: "LU", dialCode: "352" },
  { name: "Macau S.A.R.", isoCode: "MO", dialCode: "853" },
  { name: "Madagascar", isoCode: "MG", dialCode: "261" },
  { name: "Malawi", isoCode: "MW", dialCode: "265" },
  { name: "Malaysia", isoCode: "MY", dialCode: "60" },
  { name: "Maldives", isoCode: "MV", dialCode: "960" },
  { name: "Mali", isoCode: "ML", dialCode: "223" },
  { name: "Malta", isoCode: "MT", dialCode: "356" },
  { name: "Man (Isle of)", isoCode: "IM", dialCode: "44-1624" },
  { name: "Marshall Islands", isoCode: "MH", dialCode: "692" },
  { name: "Martinique", isoCode: "MQ", dialCode: "596" },
  { name: "Mauritania", isoCode: "MR", dialCode: "222" },
  { name: "Mauritius", isoCode: "MU", dialCode: "230" },
  { name: "Mayotte", isoCode: "YT", dialCode: "262" },
  { name: "Mexico", isoCode: "MX", dialCode: "52" },
  { name: "Micronesia", isoCode: "FM", dialCode: "691" },
  { name: "Moldova", isoCode: "MD", dialCode: "373" },
  { name: "Monaco", isoCode: "MC", dialCode: "377" },
  { name: "Mongolia", isoCode: "MN", dialCode: "976" },
  { name: "Montenegro", isoCode: "ME", dialCode: "382" },
  { name: "Montserrat", isoCode: "MS", dialCode: "1-664" },
  { name: "Morocco", isoCode: "MA", dialCode: "212" },
  { name: "Mozambique", isoCode: "MZ", dialCode: "258" },
  { name: "Myanmar", isoCode: "MM", dialCode: "95" },
  { name: "Namibia", isoCode: "NA", dialCode: "264" },
  { name: "Nauru", isoCode: "NR", dialCode: "674" },
  { name: "Nepal", isoCode: "NP", dialCode: "977" },
  { name: "Netherlands", isoCode: "NL", dialCode: "31" },
  { name: "Netherlands Antilles", isoCode: "AN", dialCode: "599" },
  { name: "New Caledonia", isoCode: "NC", dialCode: "687" },
  { name: "New Zealand", isoCode: "NZ", dialCode: "64" },
  { name: "Nicaragua", isoCode: "NI", dialCode: "505" },
  { name: "Niger", isoCode: "NE", dialCode: "227" },
  { name: "Nigeria", isoCode: "NG", dialCode: "234" },
  { name: "Niue", isoCode: "NU", dialCode: "683" },
  { name: "Norfolk Island", isoCode: "NF", dialCode: "672" },
  { name: "Northern Mariana Islands", isoCode: "MP", dialCode: "1-670" },
  { name: "Norway", isoCode: "NO", dialCode: "47" },
  { name: "Oman", isoCode: "OM", dialCode: "968" },
  { name: "Pakistan", isoCode: "PK", dialCode: "92" },
  { name: "Palau", isoCode: "PW", dialCode: "680" },
  { name: "Palestinian Territory Occupied", isoCode: "PS", dialCode: "970" },
  { name: "Panama", isoCode: "PA", dialCode: "507" },
  { name: "Papua new Guinea", isoCode: "PG", dialCode: "675" },
  { name: "Paraguay", isoCode: "PY", dialCode: "595" },
  { name: "Peru", isoCode: "PE", dialCode: "51" },
  { name: "Philippines", isoCode: "PH", dialCode: "63" },
  { name: "Pitcairn Island", isoCode: "PN", dialCode: "64" },
  { name: "Poland", isoCode: "PL", dialCode: "48" },
  { name: "Portugal", isoCode: "PT", dialCode: "351" },
  { name: "Puerto Rico", isoCode: "PR", dialCode: "1-787" },
  { name: "Puerto Rico", isoCode: "PR", dialCode: "1-939" },
  { name: "Qatar", isoCode: "QA", dialCode: "974" },
  { name: "Reunion", isoCode: "RE", dialCode: "262" },
  { name: "Romania", isoCode: "RO", dialCode: "40" },
  { name: "Russia", isoCode: "RU", dialCode: "7" },
  { name: "Rwanda", isoCode: "RW", dialCode: "250" },
  { name: "Saint Helena", isoCode: "SH", dialCode: "290" },
  { name: "Saint Kitts And Nevis", isoCode: "KN", dialCode: "1-869" },
  { name: "Saint Lucia", isoCode: "LC", dialCode: "1-758" },
  { name: "Saint Pierre and Miquelon", isoCode: "PM", dialCode: "508" },
  { name: "Saint Vincent And The Grenadines", isoCode: "VC", dialCode: "1-784" },
  { name: "Saint-Barthelemy", isoCode: "BL", dialCode: "590" },
  { name: "Saint-Martin (French part)", isoCode: "MF", dialCode: "590" },
  { name: "Samoa", isoCode: "WS", dialCode: "685" },
  { name: "San Marino", isoCode: "SM", dialCode: "378" },
  { name: "Sao Tome and Principe", isoCode: "ST", dialCode: "239" },
  { name: "Saudi Arabia", isoCode: "SA", dialCode: "966" },
  { name: "Senegal", isoCode: "SN", dialCode: "221" },
  { name: "Serbia", isoCode: "RS", dialCode: "381" },
  { name: "Seychelles", isoCode: "SC", dialCode: "248" },
  { name: "Sierra Leone", isoCode: "SL", dialCode: "232" },
  { name: "Singapore", isoCode: "SG", dialCode: "65" },
  { name: "Slovakia", isoCode: "SK", dialCode: "421" },
  { name: "Slovenia", isoCode: "SI", dialCode: "386" },
  { name: "Solomon Islands", isoCode: "SB", dialCode: "677" },
  { name: "Somalia", isoCode: "SO", dialCode: "252" },
  { name: "South Africa", isoCode: "ZA", dialCode: "27" },
  { name: "South Georgia", isoCode: "GS", dialCode: "500" },
  { name: "South Sudan", isoCode: "SS", dialCode: "211" },
  { name: "Spain", isoCode: "ES", dialCode: "34" },
  { name: "Sri Lanka", isoCode: "LK", dialCode: "94" },
  { name: "Sudan", isoCode: "SD", dialCode: "249" },
  { name: "Suriname", isoCode: "SR", dialCode: "597" },
  { name: "Svalbard And Jan Mayen Islands", isoCode: "SJ", dialCode: "47" },
  { name: "Sweden", isoCode: "SE", dialCode: "46" },
  { name: "Switzerland", isoCode: "CH", dialCode: "41" },
  { name: "Syria", isoCode: "SY", dialCode: "963" },
  { name: "Taiwan", isoCode: "TW", dialCode: "886" },
  { name: "Tajikistan", isoCode: "TJ", dialCode: "992" },
  { name: "Tanzania", isoCode: "TZ", dialCode: "255" },
  { name: "Thailand", isoCode: "TH", dialCode: "66" },
  { name: "Togo", isoCode: "TG", dialCode: "228" },
  { name: "Tokelau", isoCode: "TK", dialCode: "690" },
  { name: "Tonga", isoCode: "TO", dialCode: "676" },
  { name: "Trinidad And Tobago", isoCode: "TT", dialCode: "1-868" },
  { name: "Tunisia", isoCode: "TN", dialCode: "216" },
  { name: "Turkey", isoCode: "TR", dialCode: "90" },
  { name: "Turkmenistan", isoCode: "TM", dialCode: "993" },
  { name: "Turks And Caicos Islands", isoCode: "TC", dialCode: "1-649" },
  { name: "Tuvalu", isoCode: "TV", dialCode: "688" },
  { name: "Uganda", isoCode: "UG", dialCode: "256" },
  { name: "Ukraine", isoCode: "UA", dialCode: "380" },
  { name: "United Arab Emirates", isoCode: "AE", dialCode: "971" },
  { name: "United Kingdom", isoCode: "GB", dialCode: "44" },
  { name: "United States", isoCode: "US", dialCode: "1" },
  { name: "United States Minor Outlying Islands", isoCode: "UM", dialCode: "1" },
  { name: "Uruguay", isoCode: "UY", dialCode: "598" },
  { name: "Uzbekistan", isoCode: "UZ", dialCode: "998" },
  { name: "Vanuatu", isoCode: "VU", dialCode: "678" },
  { name: "Vatican City State (Holy See)", isoCode: "VA", dialCode: "379" },
  { name: "Venezuela", isoCode: "VE", dialCode: "58" },
  { name: "Vietnam", isoCode: "VN", dialCode: "84" },
  { name: "Virgin Islands (British)", isoCode: "VG", dialCode: "1-284" },
  { name: "Virgin Islands (US)", isoCode: "VI", dialCode: "1-340" },
  { name: "Wallis And Futuna Islands", isoCode: "WF", dialCode: "681" },
  { name: "Western Sahara", isoCode: "EH", dialCode: "212" },
  { name: "Yemen", isoCode: "YE", dialCode: "967" },
  { name: "Zambia", isoCode: "ZM", dialCode: "260" },
  { name: "Zimbabwe", isoCode: "ZW", dialCode: "263" },
];

export const COUNTRIES: CountryOption[] = RAW_COUNTRIES.map((c) => ({
  name: c.name,
  isoCode: c.isoCode,
  dialCode: normalizeDialCode(c.dialCode),
})).filter((c) => c.isoCode && c.name && c.dialCode);

export const DEFAULT_COUNTRY = COUNTRIES.find((c) => c.isoCode === "IN") ?? COUNTRIES[0];

export function getCountryByIsoCode(isoCode: string) {
  return COUNTRIES.find((country) => country.isoCode === isoCode) ?? DEFAULT_COUNTRY;
}
